"""empty message

Revision ID: 1fd26b0a4f8
Revises: None
Create Date: 2015-11-11 21:22:08.300107

"""

# revision identifiers, used by Alembic.
revision = '1fd26b0a4f8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('short_title', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('short_title', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('opposite_color', sa.String(), nullable=True),
    sa.Column('lat_min', sa.Float(), nullable=True),
    sa.Column('lat_max', sa.Float(), nullable=True),
    sa.Column('lon_min', sa.Float(), nullable=True),
    sa.Column('lon_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('route_Id', sa.Integer(), nullable=True),
    sa.Column('dataset', sa.Enum('agencies', 'routes', 'predictions', name='dataset', native_enum=False), nullable=True),
    sa.Column('source', sa.Enum('Nextbus', name='source', native_enum=False), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['route_Id'], ['route.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('is_departure', sa.Boolean(), nullable=True),
    sa.Column('has_layover', sa.Boolean(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('vehicle', sa.String(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('update')
    op.drop_table('stop')
    op.drop_table('direction')
    op.drop_table('route')
    op.drop_table('agency')
    op.drop_table('region')
    ### end Alembic commands ###
