"""empty message

Revision ID: 24fc3945eed
Revises: None
Create Date: 2015-11-06 23:24:49.495321

"""

# revision identifiers, used by Alembic.
revision = '24fc3945eed'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.Enum('agency', 'debug', name='dataset', native_enum=False), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update')
    ### end Alembic commands ###
