"""empty message

Revision ID: 2ac138deda5
Revises: 11eea345477
Create Date: 2015-11-07 22:03:01.230717

"""

# revision identifiers, used by Alembic.
revision = '2ac138deda5'
down_revision = '11eea345477'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('short_title', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('opposite_color', sa.String(), nullable=True),
    sa.Column('lat_min', sa.Float(), nullable=True),
    sa.Column('lat_max', sa.Float(), nullable=True),
    sa.Column('lon_min', sa.Float(), nullable=True),
    sa.Column('lon_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('route_direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('route_stop',
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], )
    )
    op.add_column('update', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.add_column('update', sa.Column('source', sa.Enum('Nextbus', name='source', native_enum=False), nullable=True))
    op.create_foreign_key(None, 'update', 'agency', ['agency_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'update', type_='foreignkey')
    op.drop_column('update', 'source')
    op.drop_column('update', 'agency_id')
    op.drop_table('route_stop')
    op.drop_table('route_direction')
    op.drop_table('stop')
    op.drop_table('route')
    ### end Alembic commands ###
