"""empty message

Revision ID: 4d5f0382c6e
Revises: 2ffc362958a
Create Date: 2015-11-08 10:37:35.419416

"""

# revision identifiers, used by Alembic.
revision = '4d5f0382c6e'
down_revision = '2ffc362958a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stop_tag_key', 'stop', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('stop_tag_key', 'stop', ['tag'])
    ### end Alembic commands ###
